// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUkpHy937w30fCXvjuu3v-SbMxNNguZdQ',
    appId: '1:109740879005:web:b804088ab1e2107732b874',
    messagingSenderId: '109740879005',
    projectId: 'fluth-86ac9',
    authDomain: 'fluth-86ac9.firebaseapp.com',
    storageBucket: 'fluth-86ac9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1jIJnIfWf4TVOfM5Dx-IgI_5Hk9jnjX8',
    appId: '1:109740879005:android:6ffc65a7addb77c732b874',
    messagingSenderId: '109740879005',
    projectId: 'fluth-86ac9',
    storageBucket: 'fluth-86ac9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOG_tJJ-45yjRVDwajxBk3MHpxq8XRiT8',
    appId: '1:109740879005:ios:9cc63b965d34fe3632b874',
    messagingSenderId: '109740879005',
    projectId: 'fluth-86ac9',
    storageBucket: 'fluth-86ac9.firebasestorage.app',
    iosBundleId: 'com.example.fluth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOG_tJJ-45yjRVDwajxBk3MHpxq8XRiT8',
    appId: '1:109740879005:ios:9cc63b965d34fe3632b874',
    messagingSenderId: '109740879005',
    projectId: 'fluth-86ac9',
    storageBucket: 'fluth-86ac9.firebasestorage.app',
    iosBundleId: 'com.example.fluth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUkpHy937w30fCXvjuu3v-SbMxNNguZdQ',
    appId: '1:109740879005:web:efa536166047f45632b874',
    messagingSenderId: '109740879005',
    projectId: 'fluth-86ac9',
    authDomain: 'fluth-86ac9.firebaseapp.com',
    storageBucket: 'fluth-86ac9.firebasestorage.app',
  );
}
